== Management and monitoring

This lab will be focused on:

* Instrumenting a cluster to support metrics
* Deploying Prometheus and Grafana
* Importing prebuilt Grafana dashboard definitions for Kafka and ZooKeeper.

While OpenShift uses Grafana and Prometheus internally, we need to use separate Prometheus and Grafana instances for our applications.
For this exercise, we will install our own instance of Prometheus and Grafana for Kafka monitoring in the same namespace as the Kafka cluster.
In this case it is 'amq-streams'.

=== Cleaning up

Delete your target cluster from previous lab:

oc delete kafka/production-ready-target

oc delete KafkaMirrorMaker2/my-mm2-cluster

=== Instrumenting the Kafka cluster

We will reconfigure the `production-ready` cluster to advertise metrics.

----
oc apply -f https://raw.githubusercontent.com/RedHatWorkshops/workshop-amq-streams/master/configurations/clusters/production-ready-monitored.yaml
----

===  Prometheus, Grafana  
Installation is done !
Details - https://strimzi.io/docs/0.11.1/#kafka_metrics_configuration




=== Opening Grafana

in your browser, go to the Grafana URL:
for this workshop:

http://grafana-demo.apps.cluster-telus-b30a.telus-b30a.example.opentlc.com/

User/Password:  admin/admin123

Go to the Strimzi Kafka dashboard
Select your namespace and cluster to monitor your kafka deployment.

